name: Playwright Tests
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-folder: ["test_2_google", "test_3_saucedemo", "test_4_spokopolish"]
        browsers: ["chromium", "firefox", "webkit"]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Pytest ${{ matrix.test-folder }}
      run: pytest --tracing=retain-on-failure  ${{ matrix.test-folder }} --browser ${{ matrix.browsers }}

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-traces
        path: test-results/
